### ISSUE TITLE
Make alphabetical sorting of attributes optional

### ISSUE THREAD

**Issue by merken** [NicoVermeir/XamlStyler#28] opened 2015-01-09 12:59 UTC
XAML attributes are evaluated sequentially.
If you do not handle this carefully in your custom XAML controls, this can result in strange behavior.

For this reason i'd like to suggest to make this optional in XAML Styler.
Instead, just loop through the attrubutes as-is.

**Comment by NicoVermeir** [comment] 2015-01-13 09:18
duplicate of #21

**Closed by NicoVermeir** 2015-01-13 09:18 UTC
